# Generated by Django 5.0.2 on 2025-08-20 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('source_lat', models.FloatField()),
                ('source_lon', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lon', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('hour', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('day_type', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=100)),
                ('event_flag', models.BooleanField(default=False)),
                ('route_type', models.CharField(max_length=50)),
                ('congestion_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('suggested_mode', models.CharField(choices=[('Car', 'Car'), ('Metro', 'Metro'), ('Bike', 'Bike'), ('Walk', 'Walk')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
