# Generated by Django 4.2 on 2026-04-08 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("predictor", "0002_analytics_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedscenario",
            options={"ordering": ["-visit_count", "-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="prediction",
            name="predictor_p_user_id_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="prediction",
            name="predictor_p_city_created_idx",
        ),
        migrations.RemoveField(
            model_name="triphistory",
            name="parking_cost",
        ),
        migrations.AlterField(
            model_name="prediction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="routeoption",
            name="route_details",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="analyticssnapshot",
            unique_together={("city", "date", "hour")},
        ),
        migrations.AlterUniqueTogether(
            name="peakhourpattern",
            unique_together={("city", "weekday", "hour", "route_type")},
        ),
        migrations.AlterUniqueTogether(
            name="predictionaccuracy",
            unique_together={("city", "date")},
        ),
    ]
